---
- name: make a build dir
  file: state=directory name=/root/hbase-master-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/hbase-master-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/hbase-master-dockerized/start.sh mode=0755

- name: build a Docker image for HBase master
  command: docker build -t gitinsky/hbase-master:0.1.2 --rm /root/hbase-master-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/hbase-master:latest --rm /root/hbase-master-dockerized
